name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build dependencies
      run: make
      
    - name: Unit testing
      run: make test
      
    - name: Memory leaks testing
      run: make leaks
      
    - name: Clean repository
      run: make clean
